export { default as Navbar } from '@/components/UI/Navbar'
export { default as Footer } from '@/components/UI/Footer'
export { default as ServiceCard } from '@/components/UI/ServiceCard'
export { default as WhatsAppBtn } from '@/components/UI/WhatsAppBtn'
export { Modal } from '@/components/UI/Modal'
export { default as FormPolitics } from '@/components/Forms/FormPolitics'